# Generated by Django 3.2.9 on 2021-11-03 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('question_code', models.TextField(default='')),
                ('question_type', models.SmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'High')], default=1)),
                ('question_time', models.SmallIntegerField(choices=[(1, '15 min'), (2, '25 min'), (3, '30 min')], default=1)),
                ('lang', models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, 'C')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcases', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interpreter.questions')),
            ],
            options={
                'verbose_name_plural': 'TestCases',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
    ]
