# Generated by Django 3.2.9 on 2021-11-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpriv',
            name='end_time',
            field=models.CharField(default='23:51:53.687', max_length=1000),
        ),
        migrations.AlterField(
            model_name='adminpriv',
            name='start_time',
            field=models.CharField(default='23:51:53.687', max_length=1000),
        ),
    ]
