# Generated by Django 3.2.9 on 2021-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interpreter', '0002_auto_20211111_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpriv',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='adminpriv',
            name='start_time',
        ),
        migrations.AddField(
            model_name='adminpriv',
            name='time',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
